### Testing API
GET http://localhost:3000/api

### Register
POST http://localhost:3000/api/auth/register
Content-type: application/json

{
    "name": "Ramit Pandey",
    "email": "ramitpandey2002@gmail.com",
    "password": "Clashofclan1@"
}

### Login
POST http://localhost:3000/api/auth/login
Content-type: application/json

{
    "email": "ramitpandey2002@gmail.com",
    "password": "Clashofclan1@"
}

### User
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw

### Book Input
POST http://localhost:3000/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw

{
    "title": "sublime art of not giving a f*ck",
    "summary": "This book is about how to live a life without worrying too much about what others"
}

### Book Details
GET http://localhost:3000/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw

### Filter
GET http://localhost:3000/api/books/filter?dateOrder=newest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw

### Update
PUT http://localhost:3000/api/books/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw

{
    "title": "JP",
    "summary": ""
}

### Delete
DELETE http://localhost:3000/api/books/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0fSwiaWF0IjoxNzUwNzA0ODc0LCJleHAiOjE3NTA3MDg0NzR9.37cMBOxzRU4R-2o6-IlalJJXVM-2EcXH1cCXnrSJPhw
